version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: hubtown_postgres
    restart: always
    environment:
      POSTGRES_USER: hubtown_user
      POSTGRES_PASSWORD: hubtown_pass
      POSTGRES_DB: hubtown_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: hubtown_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: hubtown_user
      RABBITMQ_DEFAULT_PASS: hubtown_pass
      # Para usar vhost dedicado, crie-o via UI e ajuste a URL do cliente (ex.: /hubtown)
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  rabbitmq_data:
