name: Docs Link Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install lychee
        uses: lycheeverse/lychee-action@v1
        with:
          # Read config from repository
          args: --config .lychee.toml --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
